import { getAuth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import authOwner from "@/lib/authOwner";
import prisma from "@/lib/prisma";
import { BookingStatus, LocationType } from "@prisma/client";

interface BookingUpdatePayload {
  BookingId: string;
  status: BookingStatus;
}

interface NestedItemDetails {
  name: string;
  price: number;
}

interface SchemaBookingItem {
  id: string;
  bookingId: string;
  itemId: string;
  item: NestedItemDetails | null;
}

interface SchemaUserRecord {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string;
  phone: string | null;
  image: string | null;
}

interface BaseBookingWithRelations {
  id: string;
  startTime: Date;
  endTime: Date;
  status: BookingStatus;
  locationType: LocationType;
  totalAmount: number | null;
  notes: string | null;
  queueCode: string | null;
  paymentStatus: string | null;
  createdAt: Date;
  updatedAt: Date;
  businessId: string;
  userId: string;
  staffId: string | null;
  user: SchemaUserRecord | null;
  address: unknown | null;
  items: SchemaBookingItem[];
}

// ✅ POST: Allow verified vendor space owners to alter specific booking slots (Confirm/Cancel/Complete)
export async function POST(request: NextRequest) {
  try {
    const { userId: clerkId } = getAuth(request);
    if (!clerkId)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const businessId = await authOwner(clerkId);
    if (!businessId)
      return NextResponse.json(
        { error: "Vendor account mapping required" },
        { status: 401 },
      );

    const body: BookingUpdatePayload = await request.json();
    const { BookingId, status } = body;

    if (!BookingId || !status) {
      return NextResponse.json(
        { error: "Missing parameters: BookingId or status designation" },
        { status: 400 },
      );
    }

    await prisma.booking.update({
      where: { id: BookingId, businessId: businessId },
      data: { status },
    });

    return NextResponse.json(
      { message: "Appointment status changed and updated successfully" },
      { status: 200 },
    );
  } catch (error: unknown) {
    console.error("BUSINESS_BOOKING_STATUS_POST_ERROR:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}

// ✅ GET: Fetch all historic and live bookings formatted explicitly for frontend components
export async function GET(request: NextRequest) {
  try {
    const { userId: clerkId } = getAuth(request);
    if (!clerkId)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const businessId = await authOwner(clerkId);
    if (!businessId)
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    // Inside your backend bookings route file -> GET method block:
    const bookings = await prisma.booking.findMany({
      where: { businessId },
      include: {
        user: {
          select: {
            id: true,
            firstName: true,
            lastName: true,
            email: true,
            phone: true,
            image: true,
          },
        },
        address: true,
        items: {
          include: {
            item: {
              select: {
                name: true,
                price: true,
              },
            },
          },
        },
      },
      // 🛠️ CRITICAL BLOCK FIX: Swapped 'startTime' for 'createdAt' to sort by transaction booking logs!
      orderBy: {
        createdAt: "desc", // "desc" ensures that the latest created booking sits right at the top
      },
    });

    const formattedBookings = (
      bookings as unknown as BaseBookingWithRelations[]
    ).map((booking: BaseBookingWithRelations) => {
      // 🛠️ CRITICAL FIXED BLOCK: Destructures position [0] safely to extract the correct index record row completely typesafe
      const bookingItemsArray = booking.items || [];
      const [firstRelationRecord] = bookingItemsArray;
      const coreItemMetadata = firstRelationRecord
        ? firstRelationRecord.item
        : null;

      return {
        id: booking.id,
        startTime: booking.startTime
          ? booking.startTime.toISOString()
          : new Date().toISOString(),
        endTime: booking.endTime
          ? booking.endTime.toISOString()
          : new Date().toISOString(),
        status: booking.status,
        notes: booking.notes,
        createdAt: booking.createdAt
          ? booking.createdAt.toISOString()
          : new Date().toISOString(),

        // 🔒 Explicit Root Mapping: Ensures that the true passcode value generated by your app remains permanently locked to this customer
        queueCode: booking.queueCode || "NO-CODE",
        paymentStatus: booking.paymentStatus || "PENDING",

        user: {
          firstName: booking.user?.firstName || "Client",
          lastName: booking.user?.lastName || "Profile",
          email: booking.user?.email || "N/A",
          phone: booking.user?.phone || "N/A",
        },

        item: {
          name: coreItemMetadata?.name || "General Treatment",
          price: booking.totalAmount || coreItemMetadata?.price || 0,
          duration: null,
        },
      };
    });

    return NextResponse.json({ bookings: formattedBookings }, { status: 200 });
  } catch (error: unknown) {
    console.error("BUSINESS_BOOKINGS_GET_ERROR:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
